<%
FULL_NAME_CAPS = "_"..string.upper(this.namespace).."_"..string.upper(this.name).."_";
FULL_NAME_CAMEL = capitalizedString(this.namespace).."_"..capitalizedString(this.name);
%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

#ifndef <%= FULL_NAME_CAPS %>

#import <Foundation/Foundation.h>

#import "<%= FULL_NAME_CAMEL %>Base.h"

@interface <%= FULL_NAME_CAMEL %> : <%= FULL_NAME_CAMEL %>Base
{
	
	
}

@end

#endif