<%
FULL_NAME_CAPS = "_"..string.upper(this.namespace).."_"..string.upper(this.name).."BASE".."_";
CAP_NAME = capitalizedString(this.name);
FULL_NAME_CAMEL = capitalizedString(this.namespace).."_"..capitalizedString(this.name).."Base";
%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

#import "<%= FULL_NAME_CAMEL %>.h"
#import "<%= capitalizedString(this.namespace) %>_XMLLoader.h"
<% -- check for ENUMs defined in other namespaces and load their XMLLoaders as needed
local namespaces = {};
for k,v in pairs(this.attributes) do
	if (isEnumForItem(v) and v.type.namespace ~= nil and v.type.namespace ~= this.namespace and namespaces[v.type.namespace] == nil) then
		namespaces[v.type.namespace] = true;
		gaxb_print("#import \""..v.type.namespace.."_XMLLoader.h\"\n");
	end
end
%>

@interface NSData (NSDataAdditions)

+ (NSString *) encode:(NSData *) rawBytes;
+ (NSString *) encode:(const uint8_t *) input length:(NSInteger) length;
+ (NSData *) decode:(const char *) string length:(NSInteger) inputLength;
+ (NSData *) decode:(NSString *) string;

@end

@implementation <%= FULL_NAME_CAMEL %>
<% if (hasSuperclass(this) == false) then %>
@synthesize parent;
@synthesize uid;
@synthesize originalValues;

- (id) gaxb_init { return self; }
- (void) gaxb_dealloc {  }
- (void) gaxb_loadDidComplete {  }
- (void) gaxb_valueWillChange: (NSString *)_name {  }
- (void) gaxb_valueDidChange: (NSString *)_name {  }
<% end %>
- (id) init 
{
	if ((self = [super init])) 
	{
		if (!gaxb_init_called)
		{
			gaxb_init_called=YES;
			[self gaxb_init];
		}
		
		if(!originalValues)
		{
			originalValues = [NSMutableDictionary dictionary];
		}
		
		<%
		for k,v in pairs(this.sequences) do
			if (v.name == "any") then %>	
		if(!anys)
		{
			anys = [NSMutableArray array];
		}<%
			elseif(isPlural(v)) then %>
		<%= pluralName(v.name) %> = [NSMutableArray array];<%	
			end	
		end 
		for k,v in pairs(this.attributes) do
			if (v.default ~= nil) then %>
		[self set<%= capitalizedString(v.name) %>WithString: @"<%= v.default %>"]; <%
			end
		end
%>
	}
	
	return self;
}

- (void) dealloc 
{
	originalValues = nil;
	
	if (!gaxb_dealloc_called)
	{
		gaxb_dealloc_called = YES;
		[self gaxb_dealloc];
	}
	
<%
	for k,v in pairs(this.attributes) do
		if (isObject(v)) then
			gaxb_print("\t"..v.name.." = nil;\n")
		end
	end
	for k,v in pairs(this.sequences) do
		if (v.name == "any") then
			gaxb_print("\tanys=nil;\n")
		elseif(isPlural(v)) then
			gaxb_print("\t"..pluralName(v.name).."=nil;\n")
		else
			gaxb_print("\t"..v.name.."=nil;\n")
		end
	end
%>
}

- (NSDictionary *) validAttributes
{
	NSMutableDictionary* validAttributes = [NSMutableDictionary dictionaryWithObjectsAndKeys:
<%

	for k,v in pairs(this.attributes) do
		--printAllKeys(v)
		gaxb_print("\t\t\t@\""..simpleTypeForItem(v).."\", @\""..v.name.."\",\n")
	end
	if (this.mixedContent) then
		gaxb_print("\t\t\t@\"string\", @\"MixedContent\",\n");
	end
	for k,v in pairs(this.sequences) do
		if (v.name == "any") then
			gaxb_print("\t\t\t@\"any[]\", @\"anys\",\n")
		elseif(isPlural(v)) then
			gaxb_print("\t\t\t@\""..simpleTypeForItem(v).."[]\", @\""..pluralName(v.name).."\",\n")
		else
	 		gaxb_print("\t\t\t@\""..simpleTypeForItem(v).."\", @\""..v.name.."\",\n")
		end
	end
%>			nil];
	<% if (hasSuperclass(this) == true) then %>
	[validAttributes addEntriesFromDictionary:[super validAttributes]];
	<% end %>
	return validAttributes;
}

#ifdef ANDROID
- (void) setValue:(id)_value forKey:(NSString *)_key 
{
 	if([_value isKindOfClass:[NSString class]]) 
	{
<%
		for k,v in pairs(this.attributes) do
			--printAllKeys(v)
			gaxb_print("\t\tif([_key isEqual:@\""..v.name.."\"]) { [self set"..capitalizedString(v.name).."WithString:_value]; return; }\n")
		end
%>
    	SEL selector = NSSelectorFromString([NSString stringWithFormat:@"set%@WithString:", [_key capitalizedString]]);
		[self performSelector:selector withObject:_value]; 
		return;
  	}

	[super setValue:_value forKey:_key];
}
#endif

- (void) setValue:(id)value forUndefinedKey:(NSString *)key { }

<%
	for k,v in pairs(this.attributes) do
		local capName = capitalizedString(v.name);
%>
@synthesize <%= v.name %>;
@synthesize <%= v.name %>Exists;<%
if (isObject(v)) then  %>
- (void) set<%= capName %>:(<% if (v.type == "string") then gaxb_print("NSString *") else gaxb_print(typeForItem(v)) end %>)v 
{<% if (typeForItem(v) ~= "NSString *") then %>
	if([v isKindOfClass:[NSString class]]) 
		return [self set<%= capName %>WithString:(NSString *)v];
	<% end %>
	
	<%= v.name %>Exists=YES; <%
	if  (v.type == "string") then %>
	if ([v isKindOfClass:[NSString class]] == NO) 
	{ 
		v = [v description]; 
	} <%
	end %>
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = v;
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"]; 
}<%
else %>
- (void) set<%= capName %>:(<%= typeForItem(v) %>)v 
{ 
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = v; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"]; 
}
<%if (isEnumForItem(v) == false) then%>
- (void) set<%= capName %>WithObject:(<%= OBJECTMAP[typeNameForItem(v)] %>)v 
{ 
<%	if (typeNameForItem(v)=="BOOL") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v boolValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (typeNameForItem(v)=="float") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v floatValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (typeNameForItem(v)=="short") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v shortValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (typeNameForItem(v)=="int") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v intValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (typeNameForItem(v)=="long") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v intValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (typeNameForItem(v)=="double") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v doubleValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (typeNameForItem(v)=="char") then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v intValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% elseif (isEnumForItem(v)) then %>
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = [v intValue]; 
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"];
<% else %>
	// bleh 
<% end %>
}
- (id) <%= v.name %>AsObject
{ 
<%	if (typeNameForItem(v)=="BOOL") then %>
	return [NSNumber numberWithBool:<%= v.name %>];
<% elseif (typeNameForItem(v)=="float") then %>
	return [NSNumber numberWithFloat:<%= v.name %>];
<% elseif (typeNameForItem(v)=="short") then %>
	return [NSNumber numberWithShort:<%= v.name %>];
<% elseif (typeNameForItem(v)=="int") then %>
	return [NSNumber numberWithInt:<%= v.name %>];
<% elseif (typeNameForItem(v)=="long") then %>
	return [NSNumber numberWithLong:<%= v.name %>];
<% elseif (typeNameForItem(v)=="double") then %>
	return [NSNumber numberWithFloat:<%= v.name %>];
<% elseif (typeNameForItem(v)=="char") then %>
	return [NSNumber numberWithInt:<%= v.name %>];
<% elseif (isEnumForItem(v)) then %>
	return [NSNumber numberWithInt:<%= v.name %>];
<% else %>
	// bleh 
<% end %>
}<% end %><%
end %>	
- (NSString *) <%= v.name %>AsString {<%
if (typeNameForItem(v)=="BOOL") then
	%> return ((<%= v.name %>Exists) ? (<%= v.name %> ? @"true" : @"false") : nil); <%
elseif (typeNameForItem(v)=="float") then 
	%> return ((<%= v.name %>Exists) ? [[NSNumber numberWithFloat:<%= v.name %>] stringValue] : nil); <%
elseif (typeNameForItem(v)=="short") then 
	%> return ((<%= v.name %>Exists) ? [[NSNumber numberWithShort:<%= v.name %>] stringValue] : nil); <%
elseif (typeNameForItem(v)=="int" or isEnumForItem(v)) then
	%> return ((<%= v.name %>Exists) ? [[NSNumber numberWithInt:<%= v.name %>] stringValue] : nil); <%
elseif (typeNameForItem(v)=="long") then
	%> return ((<%= v.name %>Exists) ? [[NSNumber numberWithLong:<%= v.name %>] stringValue] : nil); <%
elseif (typeNameForItem(v)=="double") then
	%> return ((<%= v.name %>Exists) ? [[NSNumber numberWithDouble:<%= v.name %>] stringValue] : nil); <%
elseif (typeNameForItem(v)=="char") then 
	%> return ((<%= v.name %>Exists) ? [[NSNumber numberWithChar:<%= v.name %>] stringValue] : nil); <%
elseif (typeNameForItem(v)=="date") then 
	%> return [self dateStringFromSchema:<%= v.name %>]; <%
elseif (typeNameForItem(v)=="dateTime") then
	%> return [self dateTimeStringFromSchema:<%= v.name %>]; <%
elseif (typeNameForItem(v)=="base64Binary") then
	%> return [<%= v.name %> base64Encoding]; <%
else
	%> return [<%= v.name %> description]; <%
end %>}
- (void) set<%= capName %>WithString:(NSString *)string 
{ 	
	<%= v.name %>Exists=YES; <%	
if (typeNameForItem(v)=="BOOL") then %>
	[self set<%= capName %>:([string isEqualToString:@"true"] ? YES : NO)];
<% elseif (typeNameForItem(v)=="float") then %>
	[self set<%= capName %>:[string floatValue]];
<% elseif (typeNameForItem(v)=="short") then %>
	[self set<%= capName %>:[string shortValue]];
<% elseif (typeNameForItem(v)=="int") then %>
	[self set<%= capName %>:[string intValue]];
<% elseif (typeNameForItem(v)=="long") then %>
	[self set<%= capName %>:[string intValue]];
<% elseif (typeNameForItem(v)=="double") then %>
	[self set<%= capName %>:[string doubleValue]];
<% elseif (typeNameForItem(v)=="char") then %>
	[self set<%= capName %>:[string intValue];
<% elseif (v.type=="date") then %>
	[self set<%= capName %>:[self schemaDateFromString:string]]; 
<% elseif (v.type=="dateTime") then %>
	[self set<%= capName %>:[self schemaDateTimeFromString:string]]; 
<% elseif (v.type=="base64Binary") then %>
	[self set<%= capName %>:[NSData decode:string]]; 
<% elseif (v.type=="string") then %>
	[self set<%= capName %>:string]; 
<% elseif (isEnumForItem(v)) then %>
	[self set<%= capName %>:(<%= v.type.name %>)([[string stringByTrimmingCharactersInSet:[NSCharacterSet decimalDigitCharacterSet]] length] == 0 ? 
		[string intValue] : [[<%= capitalizedString(v.type.namespace).."_XMLLoader arrayForEnum"..capitalizedString(v.type.name) %>] indexOfObject:string])];
<% elseif (isObject(v)) then %>
	[self set<%= capName %>:[[NSClassFromString(@"<%= typeNameForItem(v) %>") alloc] initWithString:string]]; 
<% else %>
	// bleh 
<% end 
%>}

<%
	end
	if (this.mixedContent) then %>
@synthesize MixedContent;
@synthesize MixedContentExists;
-(void) setMixedContent:(NSString *)v 
{ 
    MixedContentExists=YES; 
    if([v isKindOfClass:[NSString class]] == NO) 
    { 
        v = [v description]; 
    } 
    [self gaxb_valueWillChange:@"MixedContent"]; 
    [self willChangeValueForKey:@"MixedContentAsString"]; 
    MixedContent = v; 
    [self didChangeValueForKey:@"MixedContentAsString"]; 
    [self gaxb_valueDidChange:@"MixedContent"]; 
};
- (NSString *) MixedContentAsString { return [MixedContent description]; }
- (void) setMixedContentWithString:(NSString *)string 
{ 
	MixedContentExists=YES; 
	[self setMixedContent:[[NSClassFromString(@"NSString") alloc] initWithString:string]]; 
}
<%
	end
	for k,v in pairs(this.sequences) do
		if (v.name == "any") then
%>@synthesize anys;
- (void) appendAnyWithString:(NSString *)string 
{ 
	// does this make sense?
	[anys addObject:[[NSClassFromString(@"any") alloc] initWithString:string]]; 
}
<%		elseif(isPlural(v)) then %>
@synthesize <%= pluralName(v.name) %>;<%
		else %>
@synthesize <%= v.name %>;
@synthesize <%= v.name %>Exists;<%
			if (isObject(v)) then %>
- (void) set<%= capitalizedString(v.name) %>:(<% typeForItem(v) %>)v 
{ 
	<%= v.name %>Exists=YES; 
	[self gaxb_valueWillChange:@"<%= v.name %>"]; 
	[self willChangeValueForKey:@"<%= v.name %>AsString"]; 
	<%= v.name %> = v;
	[self didChangeValueForKey:@"<%= v.name %>AsString"]; 
	[self gaxb_valueDidChange:@"<%= v.name %>"]; 
};
<%			end
		end
	end
%>	

- (void) appendXMLAttributesForSubclass:(NSMutableString *)xml
{
	[self appendXMLAttributesForSubclass:xml useOriginalValues:false];
}


- (void) appendXMLAttributesForSubclass:(NSMutableString *)xml useOriginalValues:(BOOL)useOriginalValues
{
<% if (hasSuperclass(this)) then %>	[super appendXMLAttributesForSubclass:xml useOriginalValues:useOriginalValues];
<% end
for k,v in pairs(this.attributes) do
	if (typeNameForItem(v) == "BOOL") then 
%>	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%@'", SAFESTRING(((<%= v.name %>Exists || <%= v.name %> ) ? (<%= v.name %> ? @"true" : @"false") : NULL))]; }
<% elseif (typeNameForItem(v)=="short") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%hi'", <%= v.name %>]; }
<% elseif (typeNameForItem(v)=="int" or isEnumForItem(v)) then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%i'", <%= v.name %>]; }
<% elseif (typeNameForItem(v)=="long") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%ld'", <%= v.name %>]; }
<% elseif (typeNameForItem(v)=="char") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%i'", <%= v.name %>]; }
<% elseif (typeNameForItem(v)=="float" or typeNameForItem(v)=="double") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) 
	{ 
		NSString *s = [[NSString stringWithFormat:@"%0.2f", <%= v.name %>] stringByReplacingOccurrencesOfString:@".00" withString:@""]; 
		[xml appendFormat:@" <%= v.name %>='%@'", s]; 
	}
<% elseif (v.type=="date") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%@'", [self dateStringFromSchema:<%= v.name %>]]; }
<% elseif (v.type=="dateTime") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%@'", [self dateTimeStringFromSchema:<%= v.name %>]]; }
<% elseif (v.type=="base64Binary") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%@'", [<%= v.name %> base64Encoding]]; }
<% elseif (v.type=="string") then %>
	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %> )) { [xml appendFormat:@" <%= v.name %>='%@'", SAFESTRING(<%= v.name %>)]; }
<% 	else %>	if (!useOriginalValues && (<%= v.name %>Exists || <%= v.name %>)) { [xml appendFormat:@" <%= v.name %>='%@'", SAFESTRING([<%= v.name %> description])]; }
<%	end %>
	else if([[self valueForKey:@"originalValues"] valueForKey:@"<%= v.name %>"]) { [xml appendFormat:@" <%= v.name %>='%@'", SAFESTRING([[[self valueForKey:@"originalValues"] valueForKey:@"<%= v.name %>"] description])]; }

<%end
%>

}

- (void) appendXMLElementsForSubclass:(NSMutableString *)xml
{
	[self appendXMLElementsForSubclass:xml useOriginalValues:false];
}

- (void) appendXMLElementsForSubclass:(NSMutableString *)xml useOriginalValues:(BOOL)useOriginalValues
{
<% if (this.mixedContent) then %>[xml appendFormat:@"%@", SAFESTRING(MixedContent)];<% end %>
<% if (hasSuperclass(this)) then %>	[super appendXMLElementsForSubclass:xml useOriginalValues:useOriginalValues];
<% end
for k,v in pairs(this.sequences) do
-- print(table.tostring(v))
	if (v.name == "any") then 
%>
	FAST_ENUMERATION(x,anys) { [x appendXML:xml useOriginalValues:useOriginalValues]; } 
<%	elseif (v.ref ~= nil) then 
		if (isPlural(v)) then
%>	FAST_ENUMERATION(x,<%= pluralName(v.name) %>) { [x appendXML:xml useOriginalValues:useOriginalValues]; } 
<% 		else
%>	[<%= v.name %> appendXML:xml];<%
	  	end
	elseif (isPlural(v)) then 
%>	FAST_ENUMERATION(x,<%= pluralName(v.name) %>) { [xml appendFormat:@"<<%= v.name%>>%@</<%= v.name %>>", SAFESTRING(x)]; } 
<%	else 
%>	if (<%= v.name %> && [<%= v.name %> isEqualToString:@"(null)"] == NO) { [xml appendFormat:@"<<%= v.name %>>%@</<%= v.name %>>", SAFESTRING(<%= v.name %>)]; }<%
	end
end	 
%>}

- (void) appendXML:(NSMutableString *)xml
{
	[self appendXML:xml useOriginalValues:false];
}

- (void) appendXML:(NSMutableString *)xml useOriginalValues:(BOOL)useOriginalValues
{
	[xml appendFormat:@"<<%= CAP_NAME %>"];
	if (![[parent performSelector:@selector(xmlns)] isEqualToString:@"<%= this.namespaceURL %>"])
	{ 
		[xml appendFormat:@" xmlns='<%= this.namespaceURL %>'"]; 
	} 
	[self appendXMLAttributesForSubclass:xml useOriginalValues:useOriginalValues];
	NSMutableString * elems = [NSMutableString string];
	[self appendXMLElementsForSubclass:elems useOriginalValues:useOriginalValues];
	if([elems length])
	{
		[xml appendFormat:@">"];
		[xml appendFormat:@"%@</<%= CAP_NAME %>>", elems];
	}
	else
	{
		[xml appendFormat:@"/>"];
	}
}

- (NSString *) xmlns
{
	return @"<%= this.namespaceURL %>";
}

- (NSString *) translateToXMLSafeString:(NSString *)__value
{
	NSMutableString * string = [NSMutableString stringWithString:[__value description]];
	[string replaceOccurrencesOfString:@\"&\" withString:@\"&amp;\" options:NSLiteralSearch range:NSMakeRange(0, [string length])];
	[string replaceOccurrencesOfString:@\"<\" withString:@\"&lt;\" options:NSLiteralSearch range:NSMakeRange(0, [string length])];
	[string replaceOccurrencesOfString:@\">\" withString:@\"&gt;\" options:NSLiteralSearch range:NSMakeRange(0, [string length])];
	[string replaceOccurrencesOfString:@\"\\"\" withString:@\"&quot;\" options:NSLiteralSearch range:NSMakeRange(0, [string length])];
	[string replaceOccurrencesOfString:@\"'\" withString:@\"&apos;\" options:NSLiteralSearch range:NSMakeRange(0, [string length])];
	return string;
}

- (NSString *) description 
{ 
	NSMutableString * s = [NSMutableString string]; 
	[self appendXMLAttributesForSubclass:s]; 
	return [NSString stringWithFormat:@"<<%= CAP_NAME %>%@ />", s]; 
}

- (NSDate *) dateFromString:(NSString *)date_string
				 WithFormat:(NSString *)date_format
{
	struct tm timeStruct;
	strptime((const char *)[date_string UTF8String], (const char *)[date_format UTF8String], &timeStruct);
	
	NSDateComponents *components = [[NSDateComponents alloc] init];
	[components setSecond:timeStruct.tm_sec];
	[components setMinute:timeStruct.tm_min];
	[components setHour:timeStruct.tm_hour];
	[components setDay:timeStruct.tm_mday];
	[components setMonth:timeStruct.tm_mon];
	[components setYear:timeStruct.tm_year];
	[components setWeekday:timeStruct.tm_wday];	
	
	NSCalendar *gregorian = [[NSCalendar alloc] initWithCalendarIdentifier:NSGregorianCalendar];
	return [gregorian dateFromComponents:components];
}

- (NSDate *) schemaDateTimeFromString:(NSString *)date_string
{ 
	return [self dateFromString:date_string WithFormat:@"yyyy-MM-dd HH:mm:ss"];
}

- (NSDate *) schemaDateFromString:(NSString *)date_string
{
	return [self dateFromString:date_string WithFormat:@"yyyy-MM-dd"];
}

- (NSString *) dateTimeStringFromSchema:(NSDate *)_date
{
	NSDateFormatter * date_format = [[NSDateFormatter alloc] init]; 
	[date_format setDateFormat:@"yyyy-MM-dd HH:mm:ss"]; 
	return [date_format stringFromDate:_date]; 
}

- (NSString *) dateStringFromSchema:(NSDate *)_date
{ 
	NSDateFormatter * date_format = [[NSDateFormatter alloc] init]; 
	[date_format setDateFormat:@"yyyy-MM-dd"]; 
	return [date_format stringFromDate:_date]; 
}

@end
