<%
FULL_NAME_CAPS = "_"..string.upper(this.namespace).."_"..string.upper(this.name).."BASE".."_";
CAP_NAME = capitalizedString(this.name);
FULL_NAME_CAMEL = capitalizedString(this.namespace).."_"..capitalizedString(this.name).."Base";
SUPERCLASS_OVERRIDE = ""; if (hasSuperclass(this)) then SUPERCLASS_OVERRIDE="override "; end
%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

import UIKit

public class <%= CAP_NAME %>Base<% if (hasSuperclass(this)) then %> : <%= superclassForItem(this) %><% else %> : GaxbElement<% end %> {
<% if (hasSuperclass(this) == false) then %>
    public var xmlns: String = "<%= this.namespaceURL %>"
    public var parent: GaxbElement?
    var originalValues = Dictionary<String, String> ()

    func gaxbValueWillChange(name:String) { }
    func gaxbValueDidChange(name:String) { }

    init() { }
<% else %>
    override public init() {
        super.init()
<% for k,v in pairs(this.attributes) do
     if (v.default ~= nil) then
%>        self.gaxbValueDidChange("<%= v.name %>")
<%     end
   end %>    }
<% end

local sequencesCount = 0;
local hasAnys = false;
for k,v in pairs(this.sequences) do
  sequencesCount = sequencesCount + 1;
  if (v.name == "any") then
    gaxb_print("\tpublic var anys: Array<GaxbElement> = []\n");
    hasAnys = true;
	elseif (isPlural(v)) then
  %>    public var <%= lowercasedString(pluralName(v.name)) %>: Array<<%= simpleTypeForItem(v) %>> = []
<%
  else
  %>    public var <%= lowercasedString(v.name) %>: <%= simpleTypeForItem(v) %>?
<%
	end
end

%>    <%= SUPERCLASS_OVERRIDE %>public func setElement(element: GaxbElement, key:String) {
<% if (hasSuperclass(this)) then %>        super.setElement(element, key:key)<%
  end
   if (sequencesCount > 0) then
      for k,v in pairs(this.sequences) do
        if (v.name ~= "any") then %>
        if let e = element as? <%= capitalizedString(v.name) %> {
<% if (isPlural(v)) then %>           <%= lowercasedString(pluralName(v.name)) %>.append(e)
            e.parent = self
<% else %>        <%= lowercasedString(v.name) %> = e
            e.parent = self
<%   end %>        }<%
      end
    end
 end %>
    }
<%
for k,v in pairs(this.attributes) do %>
	public var <%= v.name %>: <%= typeForItem(v) %><%
	if (v.default == nil) then %>?<% else %> = <%= v.default %><%
	end %> {
        willSet { gaxbValueWillChange("<%= v.name %>") }
        didSet { gaxbValueDidChange("<%= v.name %>") }
    }
    public var <%= v.name %>Exists: Bool {
        return <% if (v.default == nil) then %><%= v.name %> != nil<% else %> true<% end %>
    }
    func <%= v.name %>AsString() -> String {<%
 if (v.type=="string") then %>
        return <%= v.name %><% if (v.default == nil) then %>!<% end %>
<% elseif (isEnumForItem(v)) then %>
        return <%= v.name %><% if (v.default == nil) then %>!<% end %>.toRaw()
<% elseif (isGaxbTypeForItem(v)) then %>
        return <%= v.name %><% if (v.default == nil) then %>!<% end %>.toGaxbString()
<% else %>
        return <%= v.name %><% if (v.default == nil) then %>!<% end %>.toGaxbString()
<% end
%>    }
    public func set<%= capitalizedString(v.name) %>(value: String) {
<%	if (typeNameForItem(v)=="Bool") then
%>        self.<%= v.name %> = value == "true"<%
    elseif (typeNameForItem(v)=="Int") then
%>        self.<%= v.name %> = value.toInt()!<%
elseif (typeNameForItem(v)=="Float") then
%>        self.<%= v.name %> = (value as NSString).floatValue<%
elseif (typeNameForItem(v)=="Double") then
%>        self.<%= v.name %> = (value as NSString).doubleValue<%
elseif (typeNameForItem(v)=="String") then
%>        self.<%= v.name %> = value<%
elseif (isEnumForItem(v)) then
%>        type = <%= typeForItem(v) %>.fromRaw(value)!<%
elseif (isGaxbTypeForItem(v)) then
%>        <%= v.name %> =  <%= typeForItem(v) %>(gaxbString: value)<%
end %>
    }
<%
	end %>
    <%= SUPERCLASS_OVERRIDE %>public func setAttribute(value: String, key:String) {
<% if (hasSuperclass(this)) then %>        super.setAttribute(value, key:key)
<% end %>        switch key {
<% for k,v in pairs(this.attributes) do
%>            case "<%= v.name %>":
                set<%= capitalizedString(v.name) %>(value)
<% end
%>            default:
                break
        }
    }<%
-- MixedContent is a big todo
	if (this.mixedContent) then %>
@synthesize MixedContent;
@synthesize MixedContentExists;
-(void) setMixedContent:(NSString *)v
{
    MixedContentExists=YES;
    if([v isKindOfClass:[NSString class]] == NO)
    {
        v = [v description];
    }
    [self gaxb_valueWillChange:@"MixedContent"];
    [self willChangeValueForKey:@"MixedContentAsString"];
    MixedContent = v;
    [self didChangeValueForKey:@"MixedContentAsString"];
    [self gaxb_valueDidChange:@"MixedContent"];
};
- (NSString *) MixedContentAsString { return [MixedContent description]; }
- (void) setMixedContentWithString:(NSString *)string
{
	MixedContentExists=YES;
	[self setMixedContent:[[NSClassFromString(@"NSString") alloc] initWithString:string]];
}
<%
	end
%>

    <%= SUPERCLASS_OVERRIDE %>public func attributesXML(useOriginalValues:Bool) -> String {
        var xml = ""
        if useOriginalValues {
            for (key, value) in originalValues {
                xml += " \\(key)='\\(value)'"
            }
        } else {
<% for k,v in pairs(this.attributes) do
%>            if <%= v.name %>Exists {
                xml += " <%= v.name %>='\\(<%= v.name %>AsString())'"
            }
<% end
%>        }
<% if (hasSuperclass(this)) then %>
        xml += super.attributesXML(useOriginalValues)
<% end %>
        return xml
    }

    <%= SUPERCLASS_OVERRIDE %>public func sequencesXML(useOriginalValues:Bool) -> String {
        var xml = ""<%
    for k,v in pairs(this.sequences) do
      if (isPlural(v)) then %>
        for <%= lowercasedString(v.name) %> in <%= lowercasedString(pluralName(v.name)) %> {
            xml += <%= lowercasedString(v.name) %>.toXML()
        }<% else %>    xml += <%= lowercasedString(v.name) %>.toXML()<% end
    end
 if (hasSuperclass(this)) then %>
        xml += super.sequencesXML(useOriginalValues)
<% end %>
        return xml
    }

    <%= SUPERCLASS_OVERRIDE %>public func toXML(useOriginalValues:Bool) -> String {
        var xml = "<<%= CAP_NAME %>"
        if (parent == nil || parent?.xmlns != xmlns) {
            xml += " xmlns='\\(xmlns)'"
        }

        xml += attributesXML(useOriginalValues)

        var sXML = sequencesXML(useOriginalValues)
        xml += sXML == "" ? "/>" : ">\\n\\(sXML)</<%= CAP_NAME %>>"
        return xml
    }

    <%= SUPERCLASS_OVERRIDE %>public func toXML() -> String {
        return toXML(false)
    }

    <%= SUPERCLASS_OVERRIDE %>public func description() -> String {
        return toXML()
    }

}
