<%
-- Copyright (c) 2012 Small Planet Digital, LLC
-- 
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files 
-- (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, 
-- publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
-- subject to the following conditions:
-- 
-- The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-- 
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
-- FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
-- WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 %>
<%
PACKAGE_NAME = this.namespace;
CLASS_NAME = this.name;
HEADER_NAME = this.name.."Base";

IMPORTS = {}

for k,v in pairs(this.attributes) do
	local t = typeForItem(v);
	if(t == "tVector2" or t == "tVector3" or t == "tVector4" or t == "tRect" or t == "tColor") then
		IMPORTS["import com.smallplanet.PlanetCore.Types."..t..";"] = true;
	end
end
for k,v in pairs(this.sequences) do
	local t = typeForItem(v);
	if(t == "tVector2" or t == "tVector3" or t == "tVector4" or t == "tRect" or t == "tColor") then
		IMPORTS["import com.smallplanet.PlanetCore.Types."..t..";"] = true;
	end
	if (v.name == "any" or isPlural(v)) then
		IMPORTS["import java.util.List;"] = true;
	end
end
for k,v in pairs(this.appinfos) do
	local vcopy = v
	local pipepos = string.find(v, "|")
	if (pipepos ~= nil) then
		vcopy = string.sub(v, 0, pipepos-1)
	end
	IMPORTS[vcopy] = true;
end

%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

package com.smallplanet.<%= PACKAGE_NAME %>;

<%
for k,v in pairs(IMPORTS) do
	gaxb_print(k.."\n");
end
%>

public class <%= CLASS_NAME %> extends <%= HEADER_NAME %>
{
	
}


