<%
PACKAGE_NAME = this.namespace;
CLASS_NAME = this.name;
HEADER_NAME = this.name.."Base";

IMPORTS = {}

for k,v in pairs(this.attributes) do
	local t = typeForItem(v);
	if(t == "tVector2" or t == "tVector3" or t == "tVector4" or t == "tRect" or t == "tColor") then
		IMPORTS["import com.smallplanet.PlanetCore.Types."..t..";"] = true;
	end
end
for k,v in pairs(this.sequences) do
	local t = typeForItem(v);
	if(t == "tVector2" or t == "tVector3" or t == "tVector4" or t == "tRect" or t == "tColor") then
		IMPORTS["import com.smallplanet.PlanetCore.Types."..t..";"] = true;
	end
	if (v.name == "any" or isPlural(v)) then
		IMPORTS["import java.util.List;"] = true;
	end
end
for k,v in pairs(this.appinfos) do
	local vcopy = v
	local pipepos = string.find(v, "|")
	if (pipepos ~= nil) then
		vcopy = string.sub(v, 0, pipepos-1)
	end
	IMPORTS[vcopy] = true;
end

%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

package com.smallplanet.<%= PACKAGE_NAME %>;

<%
for k,v in pairs(IMPORTS) do
	gaxb_print(k.."\n");
end
%>

public class <%= CLASS_NAME %> extends <%= HEADER_NAME %>
{
	
}


