<%
FULL_NAME_CAPS = "_"..string.upper(this.namespace).."_"
FULL_NAME_CAMEL = capitalizedString(this.namespace)
%>
//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

#ifndef <%= FULL_NAME_CAPS %>
#define <%= FULL_NAME_CAPS %>

<%
	-- includes for other header files
	for k,v in pairs(schema.elements) do
		gaxb_print("#import \""..className(v)..".h\"\n")
	end
%>

<%
	-- simpleType definitions, such as enums
	for k,v in pairs(schema.simpleTypes) do
		
		local appinfo = gaxb_xpath(v.xml, "./XMLSchema:annotation/XMLSchema:appinfo");
		local enums = gaxb_xpath(v.xml, "./XMLSchema:restriction/XMLSchema:enumeration");
		
		if(appinfo ~= nil) then
			appinfo = appinfo[1].content;
		end
		
		if(appinfo == "ENUM") then
			gaxb_print("enum\n{\n")
			for k,v in pairs(enums) do
				gaxb_print("\t"..v.attributes.value..",\n")
			end
			gaxb_print("}\n")
		end
		if(appinfo == "NAMED_ENUM") then
			gaxb_print("enum\n{\n")
			for k1,v1 in pairs(enums) do
				gaxb_print("\t"..v.name.."_"..v1.attributes.value..",\n")
			end
			gaxb_print("}\n")
		end
		if(appinfo == "ENUM_MASK") then
			local i = 1
			gaxb_print("enum\n{\n")
			for k,v in pairs(enums) do
				gaxb_print("\t"..v.attributes.value.." = "..i..",\n")
				i = i * 2;
			end
			gaxb_print("}\n")
		end
		if(appinfo == "TYPEDEF") then
			for k,v in pairs(enums) do
				gaxb_print("#define "..string.upper(v.attributes.value).." @\""..v.attributes.value.."\"\n")
			end
		end
		
	end
%>


#endif
