<%
-- Copyright (c) 2012 Small Planet Digital, LLC
-- 
-- Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files 
-- (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, 
-- publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, 
-- subject to the following conditions:
-- 
-- The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
-- 
-- THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF 
-- MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE 
-- FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
-- WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 %>
<%
FULL_NAME_CAPS = "_"..string.upper(this.namespace).."_XMLLOADER_"
FULL_NAME_CAMEL = capitalizedString(this.namespace)
%>//
// Autogenerated by gaxb at <%= os.date("%I:%M:%S %p on %x") %>
//

<%

-- simpleType definitions, such as enums
for k,v in pairs(schema.simpleTypes) do
	-- only include defintions from this schema's namespace
	if (schema.namespace == v.namespace) then			
		local appinfo = gaxb_xpath(v.xml, "./XMLSchema:annotation/XMLSchema:appinfo");
		local enums = gaxb_xpath(v.xml, "./XMLSchema:restriction/XMLSchema:enumeration");
	
		if(appinfo ~= nil) then
			appinfo = appinfo[1].content;
		end
	
		if(appinfo == "ENUM") then
			gaxb_print("typedef enum\n{\n")
			for k,v in pairs(enums) do
				gaxb_print("\t"..v.attributes.value..",\n")
			end
			gaxb_print("} "..v.name..";\n\n")
		end
		if(appinfo == "NAMED_ENUM") then
			gaxb_print("typedef enum\n{\n")
			for k1,v1 in pairs(enums) do
				gaxb_print("\t"..v.name.."_"..v1.attributes.value..",\n")
				-- print(k1,table.tostring(v1))
			end
			gaxb_print("} "..v.name..";\n\n")
		end
		if(appinfo == "ENUM_MASK") then
			local i = 1
			gaxb_print("typedef enum\n{\n")
			for k,v in pairs(enums) do
				gaxb_print("\t"..v.attributes.value.." = "..i..",\n")
				i = i * 2;
			end
			gaxb_print("} "..v.name..";\n\n")
		end
		if(appinfo == "TYPEDEF") then
			for k,v in pairs(enums) do
				gaxb_print("#define "..string.upper(v.attributes.value).." @\""..v.attributes.value.."\"\n")
			end
			gaxb_print("\n");
		end
	end			
end

%>